### PR TITLE
Moar colors!

### LINKED ISSUE #1362: Some non gameplay related things i'd like to see
people for some reason ree at the idea of making non gameplay related changes but i guess ill give it a shot (i'm willing to do all these myself btw, i'm not asking anyone else to do anything)
More empire colors since there's a rather small ammount currently which means not much choice
More system and special node names since there are a lot but youll constantly see the same ones over and over
More, better tips and if possible make faction specific tips only play when loading that specific faction
on the partially gameply related changes
Take a page from my better planet gen mod and allow any planet to spawn in any star for varietys sake (tho of course hot planets on cold stars would be rather rare) + make gas giant temp chance be affected by star temp
also allow minors to have more than 1 planet in their pool also for variety's sake

### LINKED ISSUE #1466: Additional empire colors.
So since Waky said it's fine i'll be adding more empire colors but i do have 2 questions about how this works.
What's the difference between palette.xml and palettechroma.xml?
Why is palette & palettechroma different in vanilla but the same in esg (exept in one color, is that an oversight?)

Edit: for posterity i'll add what colors you can't use
white can't be used cuz it's the color of available planets (you cant tell if a planet has an outpost or not)
black obscures the ui on invasions
There's a weird gold like color that's taken by the academy (Red="255" Green="229" Blue="156")
Minors use a very light grey, a darker shade can be used tho (Red="160" Green="160" Blue="160")
Pirates use a reddish brown (Red="160" Green="101" Blue="94")
Other ai uses an orangeish white (Red="249" Green="245" Blue="229")

### LINKED ISSUE #1478: Planet order tweaks
Tweaked the planet order (called planet temperature) to be symetrical and put as giants on the extremes.
Old:
Gas Frozen > Barren > Ice > Gas Cold > Artic > Snow > Boreal > Tundra > Gas Temperate > Steppes/Ocean/Terran/Forest/Monsoon/Swamp > Atoll > Mediterranean > Savannah > Jungle > Gas Warm/Arid > Desert > Gas Hot > Ash > Lava > Gas Burning
New:
Gas Frozen > Gas Cold > Barren > Ice > Artic > Snow > Tundra > Boreal > Steppes/Ocean > Terran/Forest/Gas Temperate/Monsoon/Swamp > Atoll/Savannah > Jungle > Mediterranean > Arid > Gas Warm/Desert > Ash > Lava> Gas Hot > Gas Burning

https://github.com/wakystuf/ESG-Mod/commit/be333ab9515aa871827410f52fb18132f5005e6b

### LINKED ISSUE #1479: More Minor faction home planets.
Instead of minor factions having one set planet they now all have a unique pool they pull from when the galaxy is being generated, the pool is very inclusive but doesnt include planets that don't make sense for them and the odds are set so planets that make the most sense are more likely.

https://github.com/wakystuf/ESG-Mod/commit/5c7fb004ff56d839d619d8076b06ecf30b086902

### LINKED ISSUE #1480: More tips and names
Added 9 new tips, a few new constelation and special node names and A LOT of solar system names, also moved tips to its own folder and names also get their own folder
https://github.com/wakystuf/ESG-Mod/commit/dc4002d57d81f31911f3dc8ee7b4acf40dc66a85
https://github.com/wakystuf/ESG-Mod/commit/c09cd7339278301f615e2352e75404f9aceb48ad

### LINKED ISSUE #1481: Added small chance for random home stars
If you play with balanced home system off there's now a small chance that your star is of a different type than default.
Also since almost all factions start with blue star i changed some:
Sophon from blue star to red dwarf
Riftborn from blue star to white dwarf
Hissho from blue star to Dyson sphere
Nakalim from "blue" star to artificial star
https://github.com/wakystuf/ESG-Mod/commit/5aeb70248e260402a96983b8876aa1a8a18cf8dc
Also ordered the quest planets to be in the correct temperature and divercified their star types.
https://github.com/wakystuf/ESG-Mod/commit/bffb15fe0d75881e8ded9978ebde195fa269c634

### LINKED ISSUE #1482: Population tweaks
-Made all pops use T1 luxuries only
-Hopefully improved automation
-Moved some vanilla pop FIDSI traits to their ESG counterpart
-Added Kalgeros, guardians, super guardians and Kal’Tik’Ma who werent previously in this file
-Tweaked some Hissho replacements for Approval, creating new approval traits in the process
-As code only changes removed "Desires" & "Wills" since that's entirely cut content and added some clarifications in the future to hopefully make it easier going forward
https://github.com/wakystuf/ESG-Mod/commit/f8149e139d391efd8c032e2f4668aeb6a5f06fb9

### PR DESCRIPTION
**Pull request by Tat011**
https://github.com/wakystuf/ESG-Mod/issues/1466

### CODE REVIEW

**Comment by wakystuf** [comment]
I'll take a closer look when I have time, but a few quick questions: 
1) Is there a documented list someplace in an Issue for everything that's changing here? It looks like it's more than only the colors, right?
2) Are the changes to StarSystemNodeDefinitions simply sorting the planets into the correct temperature-order (without changing the actual planets, anomalies, etc)? That would be great if so actually--it's something that's slightly bugged me for a long time but I haven't taken the time to fix it.
3) I think it's fine to reorganize some of the localization work, as long as you're removing the relevant portions from the non-english localizations as well--is that already included in one of the files? Otherwise the translators will get very confused, I think.

**Comment by Tat011** [comment]
1 Im pretty sure all the changes that arent small tweaks i made come with a short description
2 as meantioned in the update thing, yes it changes the order of the planets to be correct and also diversifies the star types so it's not oops all white
3 I havent touched other language files

**Comment by wakystuf** [comment]
OK, got it, thanks. I went through this more carefully now and I think it generally looks good (I still need to go really really carefully through the StarSystemNodeDefinitions.xml, since that one is easy to make a mistake in). Just 2 things:
1) Please do use the Issues function for documentation (IE, create issues for the various items you're changing, and describe what changed). For GUI changes, fine to be more high-level (e.g. more names), but for the gameplay changes (e.g. Hissho pop traits), ideal to go into more detail. That way whatever poor soul does the documentation has an easier time of it.
2) For the localization changes, please make sure you make the conforming organizational changes in the alternate language equivalents (so no need to translate anything, but like for the names, just migrate the old ones over so that it uses the same organizational scheme as before). Does that make sense?

I'll also circle back on the node definitions. I think they looked fine, but want to go through them really carefully.

**Comment by captaincobbs** [comment]
Ok, only request is that you create issues for every other thing you've worked on so it can be added to the changelog

**Comment by captaincobbs** [comment]
Great job though, no complaints

**Review by captaincobbs — APPROVED** [review]

**Pull request merged**
