### PR TITLE
Cobbs changes mar

### LINKED ISSUE #737: Custom Faction Overhaul
### To Be Added (move to bottom when done)
- Cheaper Terraformation
- Trait for starting with terraformation
- Allow selection of Faction Quests
- Allow selection of Ship Hulls
- Allow selection of Starting Hero
- Allow selection of Unique Technologies
- Move UE Gameplay Affinity influence buffs to their own traits
- Population Modifier traits for +1 base planet {x}

Already Completed:
- New Cheats!
- Full vision on galaxy
- +5/10/50/100/500 CP
- FIDSI + Manpower + Approval
- Starting with Free Movement accessible
- Traits to make troop types less expensive (manpower)
- Traits to make troop types do more damage
- Traits to make troop types have more health
- Starting with Wormholes accessible
- Starting with Free Movement accessible
- Move Vodyani increased law cost to its own trait
- Make dubious breeders incompatible with riftborn, vodyani, and UC
- Make Judicious borders incompatible with unfallen and UC
- Refill manpower on fleets outside of your territory with admirals
- Remove Planet Size planet modifiers
- Population Modifier traits for FIDSI on Ecstatic

### LINKED ISSUE #827: UE Influence Changes
Remove +100% Influence Trait
Buff sources of flat influence
If a % influence trait is still needed, make a separate trait for it.

### LINKED ISSUE #1033: Fix T2 Luxury Tooltips
Separate AltTitle and Title so that I don't have to manually replace every T2 luxury's effect to get it to display properly.
To elaborate, these tooltips do not display as "from System Modernization", they instead display as "per Population" in the FIDSI breakdown.

In order to fix this, make the Title be "from System Modernization" or whatever the default thing for system development effects are (check the gui elements for the properties of the innate system modernization FIDSI), and set the AltTitle to be "{FIDSI} per Population". (I could be wrong and the orders may need to be reversed).

If this works correctly, the modernization effects should say "+x {FIDSI} per Population" on the tooltip, and "+x {FIDSI} from System Development" (or whatever) on the breakdown.

### LINKED ISSUE #1067: Make Faction Variants of Buildings Incompatible with Eachother
Example:
Make Glacial-Sanitization Laboratories incompatible with Public-Private Partnerships and vice versa.
Go through all buildings and make sure they are incompatible.

### LINKED ISSUE #1079: Re-thinking the Vaulters for fun and meaningful interaction
I’ve been tossing around some ideas for the Vaulters lately. Not only are they weak and boring to play, but they are inexcusably _neutral_ to encounter in game. They don’t have any notable desires or conflicts with the other factions. They just kinda coolin, and it sucks for everyone.

This is despite the fact that Vaulters have a pretty interesting core identity, being defensive space miners who spent their formative years in science bunkers getting chummy with pirates. Much more interesting than the Sophons on the surface. The issue, then, is that this identity isn’t manifesting in a fun play style. Hunkering down in a few easily defensible systems and waiting for a science victory is a snoozefest.

I have two suggestions that would attempt to fix this, in a very early stage of development and balance. 

### 1: Demilitarized Zones
_Vaulters’ systems benefit from increased production when none of the nodes they connect to are colonized._ 

This principle contributes to the Vaulters’ needs to play tall in carefully considered systems, while also requiring them to take up meaningful space on the galactic map. This in turn creates tension when other factions wants to occupy any of their connecting nodes. This tension scales depending on the node connectivity setting, which for the competitive ruleset is high. The resulting contested space creates sorely needed interplay and a reason for the vaulters to flex their defensive muscle.

### 2: Proactive Protectionism
_Life among the hostile empires of Auriga has instilled a pragmatic xenophobia within the Vaulters. Threats to the internal economy are to be dismantled at any cost._

The primary function of this trait would be a more efficient Raze action, with no effect on approval. This is meant to synergize with the Vaulters’ need for empty connecting nodes. This principle also has the potential to synergize with mining behemoths, as they may prove to be an effective way for the Vaulters to get the strategics they desire without needing to colonize in their demilitarized zones. This plays to their mining identity, which I like. 

I hope that this can open a new conversation about how to make the Vaulters fun to play as or against. 

_________________________________________
_________________________________________

Notes (lots of notes): 
I have no functional idea of how difficult it would be to code AI for this. I also don't know how much the ESG community cares about AI competency.

The DMZ creates a clear target for enemy factions, in that conquering one Vaulters system would open up all surrounding systems to colonization as well. This gives opposing players reason to attack an otherwise less attractive defensive powerhouse, and gives the Vaulters additional targets when reconquering or clearing space for a new system. I think this would probably be a good thing.

Important question: Are the vaulters good enough at exploration to make the choice of systems fun? I feel like those should be fun decisions.

Jury’s currently out on what kind of production bonus the DMZ would give. Some combination of FIDSI? Happiness? Resource deposit output from the systems within the DMZ? Some combination of the above?

The improved raze action would give increased meaning to Vaulters heroes’ increases to siege damage and the like. Currently the need to play tall and lack of dictatorship means that most offensive ground battles are unnecessary. Rill Kata with her siege and manpower deployment increase would do a wonderful job of defending the motherland, lol.

Vaulters may need to get a faction-specific buff to their mining behemoth output to cement their mining identity, but I’m not really experienced enough with non-Hissho miners to know.

Would the Vaulters need additional enabling in order to invade systems in their DMZ without needing to declare war? Or would there be enough deterrent to colonising within the DMZ that nobody would attempt it without declaring war on the Vaulters first? Hmmm

If the DMZ is too difficult to code for, perhaps narrowing the focus to razing and strat mining is the way to go. Less interesting interaction, though. 

Thank u for coming to my ted talk

### LINKED ISSUE #1087: Hide Hacking tooltips when Penumbra is Disabled

### LINKED ISSUE #1091: Military Behemoths
Make Behemoth Fleet-wide versions of the following coordinator modules:
- Shield Regenerators
- EMP Disruption Field
- Flotilla Shield
- Lock-On
- Shrapnel

New Modules
- Fleet Accuracy (+10% Accuracy on Fleet at a certain range?)
- Ship Cost Reduction on Orbited System
- Fleet Health
- Fleet Damage
- Fleet Evasion
- Repair Fleet to Full after Battle (one per Fleet)
- +1 Action Point after Battle (one per Fleet)
- Improved BEB
- % Damage Reduction on Behemoth

=====================
Added in #1092 
Military Behemoth Changes
- Military Behemoth CP reduced to 5
- Weapon Arcs increased to 270

These are just the potential changes I thought were possible, lmk what feedback you have

### LINKED ISSUE #1114: Make the April Fools law recurrently appear every year

### LINKED ISSUE #1116: Make pirate bases entwineable as long as they aren't "at war" with you

### LINKED ISSUE #1197: Write Lore for Mutual Agreements 1 & 2

### PR DESCRIPTION
**Pull request by captaincobbs**

### CODE REVIEW

**Comment by wakystuf** [comment]
I think most of this looks good. 3 things:
1) Am I correct that the Vaults effectively provide +1 strat deposit value to the Vaulters everywhere all the time, automatically (since they are auto-built for free, right)? In some ways this can be offset elsewhere with Filter Barges or otherwise, but I don't think they need an overall buff to their strat gen
2) I might suggest removing  the below code from the special Vault loots, to enable people to actually use them. I realize some factions like Horatio may indeed be able to easily spare 10 approval per pillage, but for many factions 10 approval will not be worth sacrificing even with the Vault extra bonuses.
```xml 
<TemporaryEffectReference Name="SystemPillageHappinessMalus"/>
```
3) Is the UE stuff still unfinished? It looked to me like you may have replaced the wrong trait (the ind to influence conversion, instead of the x2 influence), but maybe I misread.

**Comment by captaincobbs** [comment]
> 1. Am I correct that the Vaults effectively provide +1 strat deposit value to the Vaulters everywhere all the time, automatically (since they are auto-built for free, right)? In some ways this can be offset elsewhere with Filter Barges or otherwise, but I don't think they need an overall buff to their strat gen

Ah you're right, don't think that's needed anymore with the Filter Barge changes, that was from when I first made the branch.

> 2. I might suggest removing  the below code from the special Vault loots, to enable people to actually use them. I realize some factions like Horatio may indeed be able to easily spare 10 approval per pillage, but for many factions 10 approval will not be worth sacrificing even with the Vault extra bonuses.

Done, good suggestion

> 3. Is the UE stuff still unfinished? It looked to me like you may have replaced the wrong trait (the ind to influence conversion, instead of the x2 influence), but maybe I misread.

Both effects were moved to a faction trait

**Comment by captaincobbs** [comment]
What is left to do on this branch:
1. Find some way to get Forced Treaties to have 100 Influence upkeep / turn only on the person who forced the deal
2. Add the effect for the new hacking empire improvement
3. Filter Barges strategic effect

Otherwise this is basically done, though I would like to test to make sure all the diplomatic lines were put in correctly since sometimes a typo completely messes it up.

**Comment by captaincobbs** [comment]
Ok this branch is basically finished. Just waiting for:
1. Frost to finish writing diplomatic lines for forced treaties
2. Waky to do the Filter Barges strategic effect

**Comment by Arpharnator** [comment]
I've sanity checked what has been done throughout the commits and solved conflict issues

**Comment by captaincobbs** [comment]
Good for review, will have to make some fixes to the trade changes after I merge because waky made some changes that conflict with mine.

**Review by FluffiestPrincess — COMMENTED** [review]
No, I am not going to review six thousand lines of code.

**Comment by Arpharnator** [comment]
I've reviewed it again, and it looks good

**Review by Arpharnator — APPROVED** [review]

**Comment by wakystuf** [comment]
Did these ever get adjusted to account for the movement of trade down a tier? If not, then maybe push whatever changes are necessary to my branch.

Also, what were the final initial and upkeep costs for the forced diplo constructibles?

**Comment by captaincobbs** [comment]
I'll let you deal with the merge conflicts first :)

Initial Costs were the same percent increase as force peace vs peace, roughly 4-5 times I think
Upkeep Costs were 50 influence flat because I couldn't find a way to only target the initiator.

**Comment by wakystuf** [comment]
Given that it sounds like your trade stuff doesn't work, I'll just revert it except for the 1 empire improvement that I'll slot into my code. I'll probably also fiddle with the costs for the forced diplo; the up-front sounds mostly reasonable but the upkeeps I think should be more like 2x normal instead of a flat premium

**Comment by captaincobbs** [comment]
The upkeep is fine, I talked to a bunch of people and we determined making it 100 would be unfair to the person who had it proposed on them. What specifically is wrong with the trade stuff I will fix it.

**Comment by captaincobbs** [comment]
Fixed trade they added some silly modifiers onto the technology itself

**Comment by wakystuf** [comment]
Oh, are the upkeeps paid by both sides? I thought the whole point was to make it possible for one side to pay the full cost?

**Comment by captaincobbs** [comment]
There wasn't any way to exclude the victim, if you can think of a way you're welcome to try, but the way I was hoping to do it only worked on a specific type of diplomatic constructible

**Comment by wakystuf** [comment]
OK, let me think about it. Without that, the whole mechanic doesn't work

**Comment by captaincobbs** [comment]
I'd recommend you look at ways to try to make only the initiator have the upkeep, I think it is possible I'm just not smart enough to recognize it.

**Pull request merged**
