### PR TITLE
Automatons compat

### PR DESCRIPTION
**Pull request by Arpharnator**

### CODE REVIEW

**Review by captaincobbs — APPROVED** [review]
Merge when good

**Comment by Arpharnator** [comment]
@captaincobbs do you think that what i added will break anything?

**Review by captaincobbs — APPROVED** [review]
New changes look good to me, can you confirm they don't crash ESG when the mod isn't loaded, and that they don't cause any unwanted gameplay changes when the mod isn't loaded?

**Comment by Arpharnator** [comment]
for me the game isn't crashing when I launch it, and the gameplay changes should be self contained within Automatons.

Testing the stock, it works as usual
Behemoth tooltips are the same
The teleportation code doesn't induce free fidsi for everyone in the galaxy for no reason
The terran code doesn't cause any problems either

To make sure I'll get Zyngi to load this code tomorrow or after tomorrow and see what happens

**Pull request merged**
