### PR TITLE
Update ES2_Localization_1-5-2.xml

### PR DESCRIPTION
**Pull request by Arpharnator**

### CODE REVIEW

**Comment by wakystuf** [comment]
Oh, good catch; I'm not sure who did that but I'm guessing it was me? (It was almost def me.)

Shouldn't it say ClassModuleOnlyOnePerFlotilla or did we get rid of that part?

**Comment by Arpharnator** [comment]
I saw it was commented out in the code, i suspect it's fluffiest (or maybe you) who did it like this.
The problem with this is that every module that can only be put once per ship also displays the fact that the bonus that the flotilla effect doesn't stack, which makes things confusing

**Comment by Arpharnator** [comment]
image
you also get this abomination

**Comment by wakystuf** [comment]
I think this only fixes part of the issue (IE, it basically kills the tooltip about only stacking once per flotilla), so I'll tweak

**Pull request closed without merging**
