### PR TITLE
Ship cost rebalance

### PR DESCRIPTION
**Pull request by captaincobbs**
#385

### CODE REVIEW

**Comment by captaincobbs** [comment]
I'll open this to review once I test it to make sure it doesn't crash the game

**Comment by captaincobbs** [comment]
Ready to review

**Comment by captaincobbs** [comment]
Ready to review, tested and confirmed it works

**Review by Arpharnator — APPROVED** [review]
seems good, but I won't read it all lol, too long

**Comment by Arpharnator** [comment]
I mean at least the carrier code looks good

**Comment by captaincobbs** [comment]
All the hull definition files are basically the same

**Review by wakystuf — APPROVED** [review]

**Pull request merged**
