### PR TITLE
Imigration revival

### PR DESCRIPTION
**Pull request by Arpharnator**
it works, already tested

### CODE REVIEW

**Review by wakystuf — DISMISSED** [review]

**Comment by wakystuf** [comment]
No reviews until you create an Issue for documentation

**Review by wakystuf — APPROVED** [review]

**Review by captaincobbs — APPROVED** [review]
Approved but resolve your conflicts

**Comment by Arpharnator** [comment]
there wasn't any when I put it there

**Comment by captaincobbs** [comment]
It's because one of the new merge requests wacked things up

**Pull request merged**
