### PR TITLE
Minor pop cloning

### LINKED ISSUE #1364: Minor pop cloning
Only for Horatio
Allows to clone a specific minor already in the system the same way you can clone your major pop.

### PR DESCRIPTION
**Pull request by Arpharnator**
Works.

One thing to keep in mind is that the images sometimes become blank. The reason for that is because i cba turning them into very small images and instead use the large ones in the very small slots.
If anyone has balls to make a bunch of small images then do it.

### CODE REVIEW

**Comment by NoProblemWithThisAcc** [comment]
Very nice. Does this use the Population Control mod as a base?

**Comment by Arpharnator** [comment]
i used the code inside it to convert stuff fast to what i need

**Comment by wakystuf** [comment]
Looks great! 2 things:
1) I think you need to remove the old pop cloning constructible from the main constructibles file, right?
2) I would suggest removing the nobuyout tag from the minor cloning; it just adds pointless micro if someone is trying to do science conversion or something since they need to keep track of alternating indy stock

**Comment by Arpharnator** [comment]
1) no
2) just did that

**Review by wakystuf — APPROVED** [review]

**Pull request merged**
