### PR TITLE
Make Strategic Slots count for ship sell cost

### LINKED ISSUE #868: Make Strategic Slots count for ship sell cost

### LINKED ISSUE #1228: Standardise costs for module slots
The various ship modules aren't entirely standardised. Everything that has "IsLargeSlot" should also have ModuleCostMultiplier 2, a Cost of 2 (if it has a cost), and the LargeWeapon ModuleModifier.

### PR DESCRIPTION
**Pull request by FluffiestPrincess**
See linked issues.

### CODE REVIEW

**Comment by captaincobbs** [comment]
Is this good to review? And has it been tested?

**Comment by FluffiestPrincess** [comment]
I marked it as "ready for review", so yes, it's ready for review. If it wasn't ready for review, it would still be a draft and I wouldn't have requested reviews on it.

I have done some basic testing, i.e. making sure the game actually launches and that I can design ships, place modules in the Strategic slots, and build the ships without anything throwing an error, and I've seen that the properties in the SimulationViewer change. **However**, I'm not sure if the actual sell cost of the ships is being affected - I actually don't think it is, I just haven't investigated that yet.

**Comment by captaincobbs** [comment]
> I marked it as "ready for review", so yes, it's ready for review.

Just double checking, sometimes people do it on accident, and only waky can set it back to a draft.

If you aren't sure if the sell cost is being affected, maybe @wakystuf should do some testing.

**Comment by wakystuf** [comment]
Is the TradeValue increasing when you add modules into the strat slots? That's the clearest way to tell whether it's working or not (along with simply looking at the sale price)

**Comment by FluffiestPrincess** [comment]
I'll check tomorrow

**Comment by wakystuf** [comment]
In my testing, this seems to partially work. In particular:
* The strategic costs are getting pushed into tradevalue just fine
* The extra module costs which are on non-Large weapon slots work fine
* The extra module costs on Large weapon slots are getting quadruped (instead of only doubled)
* The extra module costs on defense and support slots don't work at all (without going through the code, my guess is that it's because support and defense modules push their cost increases directly into ClassShip; they don't store that value locally at all)

**Comment by wakystuf** [comment]
What is the latest on this? Should I close it? It's fine if nobody is working on it rn; no pressure

**Comment by wakystuf** [comment]
Closing due to inactivity. Feel free to reopen if work resumes

**Pull request closed without merging**
