### PR TITLE
1236 BAIE Integration

### LINKED ISSUE #1236: Integrate Better AI Empires Difficulty Changes.
First - Ive used Git before only to post bugs.  So if I do any of this wrong please let me know and I will correct.

Per request, will integrate the Better AI Empires Difficulty Changes.  This will apply only to AI Empires, and not Empires that are Player-controlled.

https://steamcommunity.com/sharedfiles/filedetails/?id=2602129157

Only the ones in the following files:

SimulationDescriptors[GameDifficulty].xml
SimulationDescriptors[Empire].xml
SimulationDescriptors[FactionTrait].xml (and the DLC versions)

### PR DESCRIPTION
**Pull request by Thom293**
Resolves #1236 

Integrates about half of the changes from my mod Better AI Empires into ESG.  

https://steamcommunity.com/sharedfiles/filedetails/?id=2602129157

ONLY changes AI Empires.  Basically, removes colonization cap for AI, Gives the "we wont build industry" races an industry buff, and and adds some other minor tweaks that are lore-friendlyish, and fixes science Behemoths for AI races.

Details are in the issue.

### CODE REVIEW

**Review by captaincobbs — COMMENTED** [review]
In SimulationDescriptors[FactionTrait].xml, can you move all the properties to be before the modifiers? Otherwise the schema starts complaining.

**Comment by captaincobbs** [comment]
Also, from what I'm seeing in SimulationDescriptors[FactionTrait].xml, those changes are not AI only.

**Comment by Thom293** [comment]
Im pretty sure they are AI only as they only exist in the AI-only difficulty fields.  But its been months since I looked/tested.  Let me know if they are not and Ill look and test again.

The way I tested is to load up say, sophons as my race, and then switched to the AI sophon player and calculated the industry they were getting from their starting planets, and (I think) they were different.  But again, its been a while.

**Comment by captaincobbs** [comment]
I checked again and I think everything is fine. I'll give this a deeper look tomorrow though and let you know if anything other than the properties needs to change.

**Comment by Arpharnator** [comment]
Remove any changes to the Serious difficulty, it's the diffuclty played with for mp and the one used for when humans disconnect from a game. 
For example if someone disconnects from a game early on and then comes back they may find themselves with a significant headstart because of the FIDSI bonuses.

In general I don't like the direction of the changes, giving 50 col cap is unreasonable and so is giving a ton of flat FIDSI on every system, including outposts of AIs.
Nobody is going to enjoy the AI plopping colonisers in their territory or in an outpost they grew for 5 turns and then still lose it.
What the AI really needs is some sort of bonus per turn, early on the AI is obnoxious as hell even though it loses it as the game goes.
Instead of starting on roids and have the player play a very questionable catchup game and then dominate the AI anyways later on, having the AI ramp up would be good.

also @captaincobbs you need to know that many will not like these changes.

**Review by Arpharnator — CHANGES_REQUESTED** [review]
remove any changes from the serious difficulty

**Comment by NoProblemWithThisAcc** [comment]
Why is Serious difficulty special for MP games? For reference here is what players currently expect from Normal: 
image

And here is the current Serious entry: 
image

**Comment by Arpharnator** [comment]
It's just how it's been established, current ruleset for games

**Comment by Arpharnator** [comment]
also i don't think these should be the actual bonus from normal, the tooltip is lying

**Comment by Thom293** [comment]
@Arpharnator Thank you for comments.  

Of course, you dont have to use any of them.  But I do think it is balanced.  At least I tried to make it so.

Im out to an adult beverage party today, but will comment and explain reasoning for changes later today or tomorrow, so you can consider.

**Comment by Thom293** [comment]
@Arpharnator 

Ok, so I understand the concern.  TLDR here:  The changes I made to Serious are not bonuses at all.  They are literally targeted at a few specific issues that bring the AI up to neutral if it built and used the same buildings as a player.  Again - they are not a buff or a bonus.  They are a catch-up mechanic to bring the AI up from negative to Zero.  As a result, I think Serious is now the "most fair AI" difficulty.

The "FlatFIDS" bonus and other changes at Impossible and Endless are different.  They are meant protect the AI from its terrible early game weakness to having a poor start or being rushed, and to simulate "Human Ingenuity" like your player that posted a screen of having 8 scouts on turn 9.  AI cant do that.  Not with this bonus.  Not with any bonus.  It does make Cravers and Nakalim very dangerous early on.  As they should be.  And 20 or 50 FlatFIDS are inconsequential and disappear late game, as intended.

Now the way-too-long version, if you care to read it:

As to the rest, I will try to address them generally, and sometimes specifically.  And to be fair - my changes were made for my mod and not tested at fast speed but once (where UC won on turn 66).  So all of the below may need tweaking.

So as background - My goal was to balance all the races to be roughly equal opponents while still maintaining game balance.  **_So - an effective AI without cheats._**   I want to set each AI slot to random, and get a decent enemy in each one.  I think I succeeded.  I may not have.  But I think I did.  I think Serious and Impossible difficulty is now the fairest most human-like AI that I can achieve (although I think I can do better with help from this team). (Later - I did add a "cheat" bonus to Endless in the final version - which I will talk about later).  Perhaps players have to play one-difficulty level lower than they normally do at first.  Is that a bad thing?

NOTE:  Vodyani are the remaining exception, and they are a whole different subject for a whole different day.

So, with that as the background:
First, the screenshot for serious difficulty shown above is literally all vanilla except for the last 3 items.  So, its essentially unchanged from vanilla except the AI can now Invade and gets bonus resources and rooting speed (which - unless I am mistaken - is the tooltip wrong?  I thought it was a 20% increase in root speed - not 2%?)

So - what are the additions I made to serious difficulty, and why?  
Basically they are very targeted changes made only to certain races who have a very specific deficiency.  They are not blanket bonuses to all races.  Essentially certain races either will not build industry buildings reliably, or at all, or way way way too late to matter.  (Most notably Predictive Logistics and AI Labor, and Sim Camps if available). This is the Sophons, Nakalim, Vaulters and Unfallen, and why they received targeted changes (and for completeness sake - Lumeris and UE will also not build industry buildings as often as they should - but performed well in the game because of their other mechanics - so I did not give them a targeted change).  Note that I dont call this a buff - because it isnt.  _It just puts them to neutral industry where they should be if they actually built industry buildings like the player and other races._  

Dont ask me to do the math again because its been a while, but generally the reason I came up with the number to give them (essentially they each get 8 bonus) is I basically did an estimate of a 4 planet system with 1 hot planet that had 25 population and Predictive Logistics and AI Labor built on it, which is roughly 250ish industry and dialed it back by 50 because I think average system size is slightly less than 4.  So an 8 bonus on my "average" system gives roughly 200 industry at max population.  i.e. it simulates that the AI build those two buildings - when they actually dont.  So - it isnt really a bonus.  Its a catchup mechanic.  It just makes them equal to the other races that do actually build those two industry buildings.  

Nakalim had a slightly different change because they dont use their relic bonus mechanic in game.  Also the AI will often not hunt for relics well.  This change addresses both, without over-buffing them.  Again it just brings them up to par.

Hissho got changed because they just suck and the AI cant handle them.  They got colonization cap removed and a bonus to simulate mining experts.  Again - just a change to bring them to par.  I CAN do a more lore friendly AI Hissho change I think, but will need help from folks here.  But this change works for now.

Horatio got a bonus because his late-game primary resource kinda sucked and the AI wont build the food to industry buildings.  So again a "if they AI used the same buildings a player would" fix.    Honestly with the changes ESG already makes to him - he may be overtuned now.  This might need to be removed.  But needs to be tested.

The Science Juggernaut change is obviously just a catch-up mechanic too, as the AI essentially missed most of their bonus.  As long as the modules in ESG still fit in the count mechanic properly, it should give the AI the correct "average" bonus they would get if they actually used them properly.  

The colonization cap removal is really no different to the huge happiness bonus the AI gets in ESG at higher difficulties.  And it almost doesnt matter.  The most I have ever seen a AI hold is 21 systems on Max size and enemy settings run on auto with no player interference.  The only point of setting it to 50 was so they AI didnt hit that penalty, which for some reason it does not handle well.  Again - this just makes it equal to a player that will research the proper techs and enact the proper laws to handle a large empire. 

Now - onto the Impossible and Endless FlatFIDS bonus:

So why FlatFIDS?  I guess we disagree here.  But I have watched many many many AI games, and the main AI weakness is not late game.  Its early game.  The Bonuses that Amplitude and the other Difficulty mods I have seen give raw planetary bonus.  Which is nice, but takes time to develop.    The AI is very very brittle to a poor start or being rushed down early game.  The FlatFIDS bonus helps protect against that.  Just look at the bonus like "an efficiency simulation of a good player making near-perfect moves over the first 20 turns."  Like I think I saw someone post they had 8 scouts built by turn 9.  Yeah.  That.  The other benefit of FlatFIDS is that since it is a flat bonus, it essentially disappears late game.  20 or 50 FlatFIDS makes a big difference early.  It is near inconsequential late game.  It it at least helps slow a player down from bum-rushing one or two weak AI at the start of the game.  Once a player has done that, they are essentially invincible for the rest of the game.  Its just a forgone conclusion.

Now, late game AI has problems for certain, but no bonus you can give it will fix them.  Ive seen AI with multiple 3000+ industry planets get steamrolled because it doesnt know how to apportion its fleets correctly.  The AIs only real chance is an early game roadblock of the player to slow it down, so it can amass ships later to harass the player and the AI can win one of the wonder or science or econ victories.  FlatFIDS helps with that. 

Now - we could probably come up with a less severe Horatio-meme "inevitability" bonus that had the AI winning a bunch of games during the flotilla pathing issue.  And if you want we can gladly test for that.  

The Impossible +20 bonus is meant to simulate human intelligence.  I think it does so.  It isnt game breaking.  I can beat it, and I stink.  Ive been playing the game for 4 less years than most of the ESG vets.

The Endless bonus is just a flat-out AI cheat - especially the +50 and +1 move.  But I mean it to simulate "human cheese" that players do all of the time.  Admittedly - I cannot beat this difficulty.  But it is intentional (I think the ESG tooltip says "You Shall Not Pass.")  But I bet some of the old ESG players can (see 8 scouts by turn 9 EDIT:  Then he posted a screen of 11 scouts by turn 7).  If they cant, it can be tuned very easily after some of your super pros get ahold of it and can or cannot beat it.  The most perfect solution would have this be a UI element in the game startup where you could choose the bonus the AI got on Endless.  Or make a new "Infinite" Difficulty with that option.

So, that is my overly long-winded explanation.  

I can remove the changes to Serious difficulty if you like.  But it isnt a bonus.  Its just a "put certain AI to neutral" change.  Since it doesnt involve FlatFIDS, It should not disrupt games too much. 

My personal opinion is that it should be tested first.  Folks can always turn the difficulty down one notch to Hard or below.  The rest can be tweaked after testing  Or you can just throw it all out and not use it.  Anything is fine.  Just let me know.  

Please let me know if you have further questions.

**Comment by Arpharnator** [comment]
My problem with the Serious difficulty lies with the fact that it's the one used by humans.
It's why im asking for the removal of the changes to that difficulty.

As for the rest well I still find this much FIDSI brutal, if I don't have to play with it it's fine

**Comment by NoProblemWithThisAcc** [comment]
The ESG ruleset could just use normal unless there is something special about Serious I'm unaware of, right? Anyways, Waky does have a point that people might be unaware of the changes so it's a good thing there's a slider for that. Perhaps you should do as Arph said and 'serious' alone but then add entries to the slider so it goes Normal, Serious, Impossible, Endless, ESG Serious, ESG Impossible, & ESG Endless. The later ones implement your changes but we should revisit the other tooltips to make sure they are correct and explain any weaknesses of worse decision-making by the AI.

This way people think they are getting something special by cranking up the difficulty, rather than us trying to explain every time that their old vanilla Endless is now more like our Impossible and our new Endless is like an Endless+. This may introduce difficult switching back to vanilla (which I consider a serious issue), but this already exists in ESG and no one seems worried about it, so I'll let it go. At least we won't have to deal with players complaining about yet another unexpected (but better) default.

**Comment by wakystuf** [comment]
Maybe we tweak this to make it a compatibility PR instead, so that we can make it a separate mod? There's a lot of good content here, but it will probably get mixed reviews from people who find the AI too hard with these changes.

**Comment by Thom293** [comment]
My personal preference would be to make it an addition to the difficulty slider as he suggests, as that addresses all of the issues raised by @Arpharnator  @wakystuf and @NoProblemWithThisAcc.  Id just prefer that over a separate mod, as there is already a separate mod with all of these changes (mine).

That Pre-supposes that its possible to add difficulty levels?  I would assume if I just Copy and paste Serious, Impossible and Endless and rename them and some UI change is made, that would solve it?  But it may not be as easy as that.

But if that works, let me know and I can make the additions pretty easily - minus any GUI related stuff that may need to happen.

**Comment by captaincobbs** [comment]
1. For the issue that he should remove changes from serious difficulty

Absolutely not, if you want a difficulty where the AI gets no additional buffs, play on normal.

2. About 50 overcolonization

I agree, I think it incentivizes the AI to colonize way too much.

3. About whether many would not like these changes

We will test them to see if so, from what I can tell, many actually do like these changes. If the competitive players do not like these changes, they can play on normal.

4. About whether this should be turned into a compatibility pr instead of a mod merge pr

I absolutely disagree, I've requested Von Zant add these changes personally in order to assist with the common complaint that ESG AI is terrible on some of the factions, and also with a common request that BAIE should be merged with ESG. These are two common pieces of feedback I receive and I see no reason why we shouldn't merge with BAIE to fix both of them.

5. About the difficulty slider changes

I don't think that's necessary, don't think any changes of that measure are needed.

**Comment by Eighth-of-Third** [comment]
I would just like to point out that we can easily change the AI difficulty played with for multiplayer games as it doesn't actually matter. We don't leave AI slots in at the start, and the AI only takes over once someone leaves; with the new suicide law implemented, even that will only leave an AI if the player forgets to commit honourable seppuku.

**Comment by wakystuf** [comment]
Hmm, OK. If @captaincobbs  is excited about this, then I'll look at it more carefully later this week. In general, most of the faction-specific changes seem good; the main area to look at would be a) the large flat FIDS bumps and b) the effects of various buffs on AI outposts, which already behave very differently from human ones (IE, they develop very very quickly).

**Comment by Thom293** [comment]
So I have made all of these changes on my local version, and tested them.  They seem to work.  But another issue has arisen.

A main reason the AI does not seem aggressive in ESG is manpower related.  Seeing it happen again made me remember It was this exact issue that caused me to quit using ESG in the first place and make my mod.  I deleted my screens recently, but I remember roughly 66 CP of fleets orbiting a planet for 40+ turns without capturing it.  That was what caused me to make my own mod.  I personally believe it should be addressed.

The below screen shows Horatio attacking a system in the latest test version.  The important thing to note is at this time **Horatio has 16,000 Empire Manpower**.  There is 210 CP of fleets in this screen - and ANOTHER 220 CP of fleets all flying out-of-starlane to get to this system to try to capture it.  So, the AI is using more than 14 end-game 30 CP fleets (430CP) to try to capture one system.  And they have been doing so for many turns.  7 full 30 CP end game fleets should be able to destroy a system in a turn or two.  But it cant because AI doesnt use manpower modules and all systems in ESG have an average of 5k manpower at this time in the game (I have seen systems with 13k manpower - 5k is just the average).  So the AI is plenty aggressive.  It just cant actually capture systems in a timely manner.

Screenshot 2022-06-06 111354

I think it is pretty easily fixed.  Some version of "give the AI a native bonus to simulate a X Tier manpower module" should be enough to help.  But it should be targeted by ship class and perhaps race.  Scouts probably should not get any.  But Protectors and up should get some kind of MP bonus.  As Light pointed out - maybe UC should be excluded.  Again - AI only so it doesnt effect multi-player games.  I just need help with the coding.  Or one of you might be able to fix it more easily on your own.

There are secondary issues of Cravers underperforming, and Vaulters for some reason only take about 16% siege damage.  Both those are separate issues and can be addressed later.  The MP issue effects every single race.

If you would like to change this, please let me know.  I will need assistance.  Or one of yall can probably fix it pretty quickly.

**Comment by Thom293** [comment]
Ok - I think I have this working.

I fixed the Manpower issue, I think, by giving AI basically a T2 Manpower module on each ship and a small empire manpower bonus to help fill them.  The AI can now conquer planets in a timely manner.  May need tweaking after playtesting.

I tweaked the cravers, who were massively underperforming by giving the AI its vanilla -25% ship cost reduction back.  

I can upload the new changes tonight for review.  Any comments before I do?

The Hissho and Vodyani both need a balance pass but are each their own semi-large project.
The AI ship designs for a few races need a balance pass, but again thats its own project.

**Comment by wakystuf** [comment]
I was out of the country for work for part of this week and have family visiting this weekend, but will go through this carefully as soon as I can find the time. The specific incremental changes you just mentioned seem fine (as long as they are AI-only), so feel free to go ahead and push those to this branch

**Comment by Thom293** [comment]
Ok deal.

And yes, I have tested each. Unless I missed something, they should all be just AI only changes.

I will say if you want something to look at it - the math on the craver ship cost reduction is strange.  I get a roughly 25% reduction, but the way the game is calculating it is very off.  It seems likes its doing two or more calculations to get it.  And I dont know why.  So I got the result I wanted, but not exactly sure what the game is using to calculate it as it doesnt come out to exactly 25%.  But its close enough it works for this purpose.  So other than that oddity - everything else comes out as the math says it should, I think.

**Comment by Thom293** [comment]
Ok, I attempted to update the same 3 files with changes.  If I messed it up let me know.

Changes are:
1. I gave a single integral T2 manpower module to each AI ship on Serious and above.  
2. I gave the Cravers their vanilla 25% ship cost reduction back, instead of just the ESG 10%.

Seems to work.  They can capture planets.  Cravers are better (But still perform worse than vanilla).

I note some of the hero skills give massive massive manpower bonuses and some systems end of with 13k manpower or more.  Those systems are still hard for AI.

May need tweaking after playtesting.  My recommendation would be that if you currently play on Endless against AI I would try Serious or Impossible first.  Vet players can probably still beat Endless though.

**Comment by wakystuf** [comment]
Generally looks good. A few things:
* I think Cobbs mentioned this too, but +50 is way high for overcol. I'd probably do +3 per difficulty, starting with 0 on Normal
* What does MaximumManpowerPerGroundBattleTurn control exactly? I wouldn't give them purely free MP, but if it's deployment then that's fine
* I think the SystemFIDSFlat is kind of backwards; the AI's issue is more the scaling than getting started. I'd probably remove that part

**Comment by Thom293** [comment]
Thank you. 

On the colony limit, It effectively doesnt matter what the number is as long as its bigger, because the AI will never get more than 13 systems or so even on the largest galaxy unless it is swallowing other empires.  I just set it really high so it would not hit the cap.  But I will change it to +10.

The manpower thing changes the deployment limit and does not grant free troops.  I think.  But I will double check.

On the flatFIDS - I am sure this is the bonus it needs.  Sure.   It does need some help in scaling late game, but Amplitude and every single other difficulty mod I could find gives scaling bonuses and it doesnt help the AI be aggressive.  THIS bonus has an immediate effect on the AI behavior early game and makes it more aggressive.  I would suggest playtesting it first.  If anything - the only complaint you will get about it is that it makes the AI too aggressive on Endless.  But that is a good thing.  Then we can scale it back.  But it is this bonus that differentiates this mod from the others.  It might even need scaling up a bit.

**Comment by Thom293** [comment]
Ok,  lowered colonization bonus to base 10 at hard and increased by 3 per difficulty level.  Practically, all this does is net the AI a few happiness points and keeps them moving.  The largest AI empire I have ever seen on Endless difficulty on the largest galaxy in my mod was 23 and that was when Cravers or Riftborn or Horatio were dominating.  ESG will slow that down considerably anyway because of the huge Manpower bonuses it already gives.

I just removed the manpower line completely.  With the new base AI addition it is probably redundant now.  May need adding back later, but can tell better after testing.

Left FlatFids the same per note above.  I hope this is ok.  Again we can tweak after testing.  For reference I tested it in my mod at 80 flatFIDS.

EDIT:  To me, the big unknown is game speed.  I dont know how these will scale with fast speed.  I did test it a few times and seemed to be ok.

**Comment by wakystuf** [comment]
Does the flat FIDS apply on outposts? If so then we should avoid that, at a minimum

**Comment by Thom293** [comment]
@wakystuf Yes it does, as intended.  It is one of the reasons this particular bonus works over all other bonuses.

It however, is not present on Serious difficulty or below.  So people can play on those if they dont wish to play with it.  So, for instance, it isnt present on the default Multiplayer difficulty.

**Comment by wakystuf** [comment]
I'll playtest later this week, but I'm very skeptical of the flat FIDS, particularly on outposts. It's very annoying when the AI colonizes over your outpost and there's not much you can do about it (or similarly annoying for the non-outpost factions that also have no recourse, like Vaulters or Unfallen)

**Comment by Thom293** [comment]
Yes.  It is intentionally annoying.

It was my impression that the goal was to make ESG AI more difficult.  Removing this will hinder that effort greatly.  And its still needs help beyond this.  Quite a bit.

My suggestion would be that it be released as-is unless there is a bug.  It can be tweaked up or down after testing.  But if it never sees the light of day, you will never know what you do or dont have.

Just my opinion.

**Comment by wakystuf** [comment]
Maybe we see if we can get a couple of volunteers to test on Endless before we merge, to see what they think about that part?

**Comment by Thom293** [comment]
Yes, whatever you like.  I would suggest Impossible though.  But up to you.  Endless is supposed to be hard.

But after playing more it seems most of these changes will have a very small impact in ESG, because of other manpower and economy changes.  ESG manpower and inflation frankly keep the AI from doing anything militarily in a timely manner after early-mid game.  

So without that particular FIDS bonus, which helps the AI early game, its just not worth making any of the changes, frankly.    Which is absolutely fine if that is what you want to do.  Just let me know what you decide.  I will cease messing with it until yall decide.

**Comment by NoProblemWithThisAcc** [comment]
If we make Endless actually impossible for humans to beat, I'll be happy. Impossible (despite the name change) I can also playtest. I'll be happy to play test both (and beat the AI in both) once it gets pushed to steam

**Comment by Thom293** [comment]
So, with the recent departure, I am not sure continuing on this project is going to be worthwhile.  So im going to go do this other thing somewhere else.   If yall decide to implement what I put up, let me know if you need assistance with it.  I will gladly help.  Otherwise Ill just leave it as-is.  Good luck.

**Review by wakystuf — APPROVED** [review]

**Comment by wakystuf** [comment]
OK, let's try this as-is, but if people complain then we can reduce the flat FIDS.

**Pull request merged**
