### PR TITLE
Horatio gameplay changes

### PR DESCRIPTION
**Pull request by Arpharnator**

### CODE REVIEW

**Comment by captaincobbs** [comment]
document

**Comment by Arpharnator** [comment]
rude honestly

**Comment by wakystuf** [comment]
Traveling on vacation this week but can take a look in a few days if you want. Just remind me if you still need my review and I haven't responded by Tues or Wed.

**Comment by wakystuf** [comment]
Don't forget that we'll need to change the various major faction quests (ex: sophons, UC, RB, Vody, maybe others?) as part of this

**Comment by Arpharnator** [comment]
don't touch my grass and create your own issues

**Comment by wakystuf** [comment]
Done :)

**Review by wakystuf — APPROVED** [review]

**Comment by wakystuf** [comment]
@Arpharnator Sorry I took a while to look at this; was on vacation last week and have been really busy with work since I got back.

I made a few minor tweaks (see what I did there?), but overall looks good. I didn't carefully read the changes to the pops and the ships, by the way, but the other stuff I looked at as carefully as I could stand.

For the migration score, I did the math basically assuming that the relevant system is a total shithole right next to the minor, which works out to about 25 migration score:
-50 approval *0.4 + SD1*5 = 25
-Then maybe ~10 empty pop slots yields adjustment of 1.2x
-Then maybe war with 1 faction out of 4 yields adjustment of 0.81x (which basically just cancels out the 1.2x, bringing it back to 25)

This way the immigrants from the minors aren't literally free no matter what, but should still be quite easy to attain if the system isn't total shit (plus with bald +40% you can probably get them even if the system is total shit...)

**Review by captaincobbs — APPROVED** [review]

**Pull request merged**
