### PR TITLE
Ratio skill bug fix + smalls booster techs tweak

### LINKED ISSUE #1526: Tweak Hero Ship Bonuses from Small Enhance Empire Improvement
The vanilla version, in addition to increasing Small's stats, also grants some module mult to Hero Ships in a very confusing and random manner.

As such I have decided to grant both of these some slight bonus to Hero Ships in a straightforward manner.

image
image

### PR DESCRIPTION
**Pull request by Arpharnator**

### CODE REVIEW

**Comment by wakystuf** [comment]
It looks like this one will have a conflict with your other PR, right? Other than that, it looks good assuming you've confirmed/tested that it works. (Code looks fine, but I didn't test)

**Comment by Arpharnator** [comment]
oh yea I didn't notice that I had taken from that WIP branch
It should be good now though

I did test it, and it works fine

**Comment by captaincobbs** [comment]
Make an issue and otherwise it looks like you're good

**Comment by Arpharnator** [comment]
https://github.com/wakystuf/ESG-Mod/issues/1526
just linked

**Review by captaincobbs — APPROVED** [review]

**Pull request merged**
