### PR TITLE
Lumeris changes

### PR DESCRIPTION
**Pull request by Arpharnator**

### CODE REVIEW

**Comment by wakystuf** [comment]
@Arpharnator I think most of this seems fine, but I made 2 changes (one is just a bugfix). Are you OK with those?

**Comment by Arpharnator** [comment]
no, make the number not 0.15, but 0.5

**Comment by wakystuf** [comment]
Oof. 0.5 is still like 4x what is it in vanilla; that seems like so much. Do you have a save you can share that shows whether that number is reasonable?

**Comment by Arpharnator** [comment]
do you ever look at numbers?
making a grand 5 science and multiplying that by 5 is a wow number

**Review by wakystuf — APPROVED** [review]

**Pull request merged**
