### PR TITLE
Penis branch

### LINKED ISSUE #872: Anomaly Enhancement
Completely disregard this document :
https://docs.google.com/document/d/1GsgUxXha4-4wWr_M5FiglITY5gUgCx-4-Q2X2qJ7TQU/edit

Actual Enhanced Anomalies Effects :
https://docs.google.com/document/d/1cYq_owRRVrCUuwQJqouTZdtsCRJ7uHQUzBQIvCgDEtE/edit

- [x] #1184
- [x] #1192
- [x] Work out how to make anomaly enhancement Ecologist-only
- [x] #1193
- [x] #1194
- [x] Reconfigure the tech tree to put anomaly enhancement techs at the right point
- [x] Balance pass
- [x] Documentation

Merge Advanced Non-Baryonics into Ontological Rev-Eng, Move Anomaly Reduction to Climate Engineering
Move Modded Terraformation to new technologies
Give the neutral / negative anomaly traits a "x anomaly is spawned on your home planet" message, only gives anomaly stats

### LINKED ISSUE #995: New Curio Rewards
(All images used are the correct size for the mod)
StarSystemImprovementWonderPopulation02Large
Immunity to Blockade Effects (Manpower, FIDSI, and Strategics) (Unique Constructible, Expensive)

StarSystemImprovementDefense4Large
-20% Enemy Invasion Manpower Limit (Unique Constructible)

### LINKED ISSUE #1385: The thumbnail for the Enhance Coral Reefs action is just a white square.

### LINKED ISSUE #1388: Law changes
Roughing It: 
- [x] Loses -10% Anomaly Reduction industry cost per turn up to 50% (15% up to 60% for republic)

All Hands Dictum:
- [x] Gains -10% Anomaly Reduction industry cost per turn up to 50% (15% up to 60% for republic)
- [x] Loses +2% Industry & +2% Science per Population Types
- [x] Gains +10% Industry / Dust / Science on System per Terraformed Hot / Temperate / Science planet respectively
- [x] Horatio variant is no longer needed

Blood From Stones:
- [x] Gains x5 Ownership Bonus from Special Nodes on Systems
- [x] New Unfallen Variant: 2x Ownership from Special Nodes on Systems
- [x] New Umbral Choir Variant: 2x Ownrship from Special Nodes on Beacons
- [x] Vodyani Variant: 5x Ownership Bonus from Special Nodes on Systems

### LINKED ISSUE #1390: Anomaly FX Fix
Make new descriptors for anomaly effects and keep the base anomaly's simulation descriptor so that effects are still applied.

# Example:
## Currently:
**Unenhanced:**
AnomalyWonder06 (has visuals)

**Enhanced:**
AnomalyWonder06 (no visuals)

## Fix:
**Unenhanced:**
AnomalyWonder06 (no effect, only for visuals)
AnomalyWonder06Effect (effect, no visuals)

**Enhanced:**
AnomalyWonder06 (no effect, only for visuals)
AnomalyWonder06EnhancedEffect (effect, no visuals)

### PR DESCRIPTION
**Pull request by captaincobbs**
Penis branch

### CODE REVIEW

**Review by Arpharnator — APPROVED** [review]
:sus:

**Comment by wakystuf** [comment]
What is the reason to change the Sci and Mil T6 laws to 28% from 30%?

**Comment by captaincobbs** [comment]
> What is the reason to change the Sci and Mil T6 laws to 28% from 30%?

I tried it a bunch in multiplayer but it was frustrating how powerful the militarist bonus was when it was so general, it was way too close to the Pacifist bonus, which is very specific. Pacifists should have the advantage when defending, that was the entire point of the law being designed that way. As it was currently, it was  just cancelling out the militarist bonus.

I tested a bit in multiplayer and it just felt right, wasn't a huge change but I felt a little difference.

**Review by captaincobbs — COMMENTED** [review]
You need to update the tooltip as well (T1 religious law changes), it doesn't auto update because of weird pathing

**Comment by wakystuf** [comment]
I think your T1 religious tooltip already was written that way; I just made them match, right?

**Comment by captaincobbs** [comment]
Oh, no you're right, I thought you were doing it to the normal law not the republic version.

**Comment by wakystuf** [comment]
This looks good, except aren't you doing the same thing twice with the hangar effect with these 2 lines?
`<Modifier TargetProperty="BonusManpowerLimit" Operation="Addition" Value="0.15" Path="ClassShip" TooltipHidden="true"/>
    <BinaryModifier TargetProperty="AdditionalGroundBattleManpowerLimit" Operation="Addition" Left="0.15" BinaryOperation="Multiplication" Right="$(MaximumShipManpower)" Path="ClassShip" SearchValueFromPath="true" TooltipHidden="true"/>`

**Comment by Arpharnator** [comment]
iirc BonusManpowerLimit is the ship's bonus storage
AdditionalGroundBatleManpowerLimit would be the deployment cap.

**Comment by captaincobbs** [comment]
BonusManpowerLimit is a property I made that specifically takes the bonus max manpower (with the 0.15 being the % bonus added to max crew used for the math) and adds it to AdditionalGroundBattleManpowerLimit (separately), and then the +15% AdditionalGroundBattleManpowerLimit is just overall. It's a bit of a weird effect but it just feels right.

**Comment by wakystuf** [comment]
Right but I'm saying those do the same thing effectively (both are +15% max MP, for a total of +30%)?

**Comment by captaincobbs** [comment]
I see what you're saying, yeah if you have 40 Crew manpower you'd effectively just get +12 deployment limit. Might as well just simplify it.

**Comment by captaincobbs** [comment]
Branch finished, lmk when its merged and added to the live version

**Comment by Arpharnator** [comment]
note that you have Boreal and Jungle with 1 food so change that first

**Comment by wakystuf** [comment]
I fiddled with the planet values to balance all of them at 20, and then 30 for gas. If this works for you guys, go ahead and merge

**Comment by captaincobbs** [comment]
Seems fine to me, I'm going ahead and merging.

**Pull request merged**
