### PR TITLE
More WAK changes 1.4.1

### PR DESCRIPTION
**Pull request by wakystuf**

### CODE REVIEW

**Review by captaincobbs — COMMENTED** [review]
You didn't update localization in other languages

**Comment by wakystuf** [comment]
You mean the deletions from the prior versions? Since usually the current release gets converted by the translators, right?

**Comment by captaincobbs** [comment]
Yes

**Comment by captaincobbs** [comment]
waky wtf 47 changed files

**Comment by wakystuf** [comment]
Santa's been busy making lots of presents for all the good boys and girls

**Pull request merged**
