### PR TITLE
1182 inconsistency in ship role icons

### LINKED ISSUE #1182: Inconsistency in ship role icons
In some places, Coordinator hulls use the "support" icon, and in other places they use "plating". There are other inconsistencies too. I'm planning to fix this so:

- Colonizers always use [colonizer]
- Explorers always use [explorer]
- Attackers always use [attacker]
- Defenders always use [plating]
- Coordinators always use [support]
- Hunters always use [duel]
- Carriers always use [carrier]
- Leechers always use [lifeforce]
- Arks always use [mothership]
- Vine ships always use [unfallen]

### PR DESCRIPTION
**Pull request by FluffiestPrincess**
Not perfect.

1. The icon being used for the Hunter ships is the wrong resolution
2. The symbol used for vineships isn't the same as the icon, but they get the point across
3. I haven't touched the SmallInverted, Medium, and MediumInverted icons because I have no idea where they get used

### CODE REVIEW

**Comment by captaincobbs** [comment]
1. What resolution does the hunter icon need to be
2. What is the original vineship icon?
3. I'll look into that, I believe it's mostly during ship combat menus.

**Comment by FluffiestPrincess** [comment]
1. The others are 24x24
2. ShipRoleRootCreatorSmall
3. Thanks!

**Comment by captaincobbs** [comment]
ShipRoleRootCreatorSmall
ShipRoleMediumSupport
ShipRoleMediumAttacker

**Comment by captaincobbs** [comment]
About 3, I'd recommend leaving them alone. Those are the icons used in the space combat flotilla menu when showing what ships are where. Every combat ship type has its own icon.

**Comment by FluffiestPrincess** [comment]
> ShipRoleRootCreatorSmall ShipRoleMediumSupport ShipRoleMediumAttacker

I'm not really sure what you want me to do with these.

**Comment by captaincobbs** [comment]
Ah I thought you had needed the icons

**Review by captaincobbs — APPROVED** [review]

**Pull request merged**
