### PR TITLE
872 anomaly enhancement

### LINKED ISSUE #872: Anomaly Enhancement
Completely disregard this document :
https://docs.google.com/document/d/1GsgUxXha4-4wWr_M5FiglITY5gUgCx-4-Q2X2qJ7TQU/edit

Actual Enhanced Anomalies Effects :
https://docs.google.com/document/d/1cYq_owRRVrCUuwQJqouTZdtsCRJ7uHQUzBQIvCgDEtE/edit

- [x] #1184
- [x] #1192
- [x] Work out how to make anomaly enhancement Ecologist-only
- [x] #1193
- [x] #1194
- [x] Reconfigure the tech tree to put anomaly enhancement techs at the right point
- [x] Balance pass
- [x] Documentation

Merge Advanced Non-Baryonics into Ontological Rev-Eng, Move Anomaly Reduction to Climate Engineering
Move Modded Terraformation to new technologies
Give the neutral / negative anomaly traits a "x anomaly is spawned on your home planet" message, only gives anomaly stats

### LINKED ISSUE #1184: Add new "Enhanced Anomalies" to the XML
At this preliminary stage they should have effects from [the google doc](https://docs.google.com/document/d/1GsgUxXha4-4wWr_M5FiglITY5gUgCx-4-Q2X2qJ7TQU/edit?usp=sharing), but never spawn naturally. They can have generic flavour text.

_Child of [Anomaly Enhancement](https://github.com/wakystuf/ESG-Mod/issues/872)_

### LINKED ISSUE #1192: Implement anomaly reduction
- [x] Set up Waky's magical anomaly reduction so that the existing anomalies can be upgraded according to the google doc
- [x] Work out how to make anomaly enhancement Ecologist-only

_Child of [Anomaly Enhancement](https://github.com/wakystuf/ESG-Mod/issues/872)_

### LINKED ISSUE #1193: Update effects (and, if necessary, tooltips) for Enhanced Anomalies
According to [the google doc](https://docs.google.com/document/d/1GsgUxXha4-4wWr_M5FiglITY5gUgCx-4-Q2X2qJ7TQU/edit?usp=sharing)

_Child of [Anomaly Enhancement](https://github.com/wakystuf/ESG-Mod/issues/872)_

### LINKED ISSUE #1194: Add flavour text for Enhanced Anomalies
according to [the google doc](https://docs.google.com/document/d/1GsgUxXha4-4wWr_M5FiglITY5gUgCx-4-Q2X2qJ7TQU/edit?usp=sharing)

_Child of [Anomaly Enhancement](https://github.com/wakystuf/ESG-Mod/issues/872)_

### PR DESCRIPTION
**Pull request by FluffiestPrincess**

### CODE REVIEW

**Comment by Arpharnator** [comment]
Currently there are 3 things remaining : 
1) Figure out how to make it so that anomalies can get "reduced" even if positive/reduced
2) Extract the images from the bigger images to make the tooltip images + some localisation (or myabe check the gui bc i entered the wrong thing)
3) Enhanced anomalies effect

**Comment by stygmaskyzoo** [comment]
2. all anomalies need this? if you tell me which size you need i can rescale them

**Comment by Arpharnator** [comment]
I've done 2)

As such that leaves : 
1) Figure out how to make it so that anomalies can get "reduced" even if positive/reduced
3) Enhanced anomalies effect

**Comment by FluffiestPrincess** [comment]
"Enhanced anomalies effect" is tracked under #1193 , I believe.

By 1), do you mean working out how to make the anomaly enhancement menu pop up even when there are neither Negative nor Mixed anomalies on the planet?

**Comment by Arpharnator** [comment]
exactly

**Comment by Arpharnator** [comment]
I pushed something that turns (hopefully i didn't miss any) every positive anomaly into a mixed one, and every mixed anlmaly into a negative one

**Comment by Arpharnator** [comment]
the reduced versions will also be mixed anomalies

**Comment by Arpharnator** [comment]
if we decide to take care of 1) by making anomalies mixed and negative in all cases, then that leaves only the coding of 3).

**Comment by FluffiestPrincess** [comment]
3) is #1193

**Comment by Arpharnator** [comment]
I know ffs, im saying the coding of the effects is what's left to be done

**Comment by FluffiestPrincess** [comment]
Sorry, I didn't realize I'd already posted that. I was just trying to make sure that whoever decides to do it assigns the issue to themselves.

**Comment by wakystuf** [comment]
For the most part I think this looks good. A few things:
1) I'll review the sim descriptor effects now
2) Does localization for these need to be update to reflect non-enhancement of negatives and non-existence of ruinous?
-EmpireImprovementAnomalyReduction1EffectOverride
-EmpireImprovementAnomalyReduction2EffectOverride
3) It probably makes sense to document how this whole thing works in 1 fresh issue instead of the batch of multiple issues that are currently circulating. Please make sure to document the political effect changes (telluric is ecologist, hero assignment is religious, gas is industrialist)

**Comment by wakystuf** [comment]
Update: I made a couple of other changes and resolved conflicts, so I think this is all set pending that tweak to the localization (I think?) and then documentation

**Comment by Arpharnator** [comment]
well negative can be enhanced, just that they get turned in to positives.
i removed the part about ruinous anomalies

**Comment by wakystuf** [comment]
Looks good. I'll merge

**Review by wakystuf — APPROVED** [review]

**Pull request merged**
