### PR TITLE
Balanced start retry finish

### LINKED ISSUE #1013: Balance start
Horatio : done (todo : fix the system's curios)
everything else : not done

In regards to custom factions, the current prerequesites to trigger the balance start is to have the same initial populations as the standard empire.
The reason for that is that if the system is made anew without removing the population in the system, the growthstock is still present and as such when starting the game you will find yourself with several hundred worth of food stockpiled and ready to use, which is not what we want.
Since the only way to deal witgh this problem is to remove the starting populations before remaking the system, it is necessary to be able to target the populations properly, thus leading to customs without the same starting pops to be unable to use it.

### PR DESCRIPTION
**Pull request by Arpharnator**
Successfully tested, passed the vibe check as well
maybe reduce amount of curios on homesys at some point but cba rn

### CODE REVIEW

**Comment by NoProblemWithThisAcc** [comment]
Quick question: can conditional statements be added to check for player traits?

ie. a custom player has a 'bad start' pick and therefore gets a different kind of home system compared to a player of the same race without that pick

**Comment by captaincobbs** [comment]
This will not work on custom factions

**Comment by wakystuf** [comment]
These look good. 2 thoughts:
1) It's fine for now, but once I get my resource spawn code working, we probably should remove the strats from most of these (let me know if you disagree).
2) How does this work for the Vaulters?

**Comment by Arpharnator** [comment]
doesn't work for vaulters

once you get the resource spawning thing going on ill remove the stuff

**Comment by wakystuf** [comment]
Sounds good. This is still marked as draft; is it all set to merge or no?

**Comment by Arpharnator** [comment]
yes you can merge i believe everything is good

**Review by wakystuf — APPROVED** [review]

**Pull request merged**
