### PR TITLE
Sophons buff

### PR DESCRIPTION
**Pull request by Arpharnator**
press approve it simply works

### CODE REVIEW

**Comment by wakystuf** [comment]
This looks good in terms of balance. I think you may need to create a GUI element for the new empire improvements though

**Comment by wakystuf** [comment]
Oh, and in the buildings change it looks like you just a) buffed the awful sophon building and b) reformatted a ton of stuff, right?

**Comment by captaincobbs** [comment]
I'd like Chaos to review this because the Sophons are his baby

**Comment by Arpharnator** [comment]
yes I reformated a bunch of stuff because it looked very ugly

**Comment by wakystuf** [comment]
Well I'm pretty sure the game is going to say that your stuff is ugly, since you didn't create a GUI element for each of them, unless I'm mistaken

**Comment by wakystuf** [comment]
@Arpharnator if we are keeping these, I think you still need GUI elements

**Comment by Arpharnator** [comment]
what conflicts

**Review by wakystuf — APPROVED** [review]

**Review by captaincobbs — CHANGES_REQUESTED** [review]
Create a list of the empire improvements, their effects, and their place on the tech tree.

Also, change the empire improvements to add to ClassPlanet instead of ClassPopulation.

**Comment by Doruk-Coskun** [comment]
Since these changes are accepted seperately in different pull requests this pull request is rejected.

**Pull request closed without merging**
