### PR TITLE
1 4 minor changes chaos

### PR DESCRIPTION
**Pull request by Doruk-Coskun**

### CODE REVIEW

**Review by captaincobbs — CHANGES_REQUESTED** [review]
Your localization file isn't indented properly, it's going to have a line break before and after the tooltip.

**Comment by Doruk-Coskun** [comment]
@captaincobbs please check again

**Review by captaincobbs — CHANGES_REQUESTED** [review]
ModuleSupportJuggernautVampirilis isn't going to disable when you have more than one of the same module on the ship, you need to change the prerequisite from targeting "ModuleSupportJuggernautVampirilis" to "ModuleSupportJuggernautCoreCrackerVampirilis"

**Review by wakystuf — CHANGES_REQUESTED** [review]
I think we agreed on 10 titanium for Sim Camps, right?

**Comment by captaincobbs** [comment]
Oh I just realized, is there an issue to link this to?

**Comment by wakystuf** [comment]
> Oh I just realized, is there an issue to link this to?

@captaincobbs  asking the real questions here :) Pretty sure the answer is "no"

**Comment by captaincobbs** [comment]
DISGUSTING!

**Comment by Doruk-Coskun** [comment]
Updated, recheck

**Review by captaincobbs — APPROVED** [review]
Looks good to me now

**Review by wakystuf — APPROVED** [review]

**Comment by wakystuf** [comment]
@Doruk-Coskun Here's the pull request that I think has no documentation

**Pull request merged**
