### PR TITLE
Replace Shield Interference Beams with Shield Interference Missiles

### LINKED ISSUE #1170: Tweak Red Beams ("Shield Interference Beam", AKA "EMP beams")
They invalidate most of the combat sandbox once unlocked since they effectively give all beams 100% crit chance and everything gets 1 shot.

### PR DESCRIPTION
**Pull request by FluffiestPrincess**
Please note this has NOT been tested. I don't have the Vaulters DLC, so while it didn't appear that the EMP effect was working, that might be due to the lack of the DLC rather than a problem with the code.

### CODE REVIEW

**Comment by FluffiestPrincess** [comment]
Also note that the shield interference beams are still available, for comparison purposes.

**Comment by wakystuf** [comment]
What is the latest on this? Should I merge this? Close it? It's fine if nobody is planning on working on it; no pressure

**Comment by wakystuf** [comment]
Closing due to inactivity. Feel free to reopen if work resumes

**Comment by FluffiestPrincess** [comment]
The latest is that I asked people who have the Vaulters DLC to test the branch, and no-one did. Since I don't have Vaulters DLC, I can't test anything myself.

**Pull request closed without merging**
