### PR TITLE
Boosted salvo health to 1 million

### LINKED ISSUE #1172: Tweak Blast Effect Battery so it can't be shot down any more
From the Discord:

> Wakystuf — 21/04/2022
> I keep forgetting to tweak BEB; it's really stupid that it can be shot down

### PR DESCRIPTION
**Pull request by FluffiestPrincess**

### CODE REVIEW

**Comment by wakystuf** [comment]
Looks like this should work. Does that SimulationDescriptor have any other properties in vanilla, or no? Just want to make sure we aren't generating a bunch of null values.

**Comment by FluffiestPrincess** [comment]
It does not. If someone can please _test this_ and make sure the Blast Effect Battery isn't still getting shot down regardless, that would be great.

**Comment by captaincobbs** [comment]
Code looks good, even if it doesn't work it would be inconsequential.

**Review by captaincobbs — APPROVED** [review]
Merge when ready.

**Pull request merged**
