### PR TITLE
Replaced Collateral Damage with Team Spirit

### LINKED ISSUE #1169: Remove Collateral Damage from the Tech Tree
Remove Collateral Damage from the tech tree and replace it with Team Spirit.

### PR DESCRIPTION
**Pull request by FluffiestPrincess**
Team Spirit is no longer available from curiosities, and Collateral Damage isn't available at all.

### CODE REVIEW

**Comment by wakystuf** [comment]
Hmm...Are you sure this code works? It looks like it will indeed properly remove Team Spirit from the curio droplists, but I don't think it will affect which one is unlocked on the tech tree, as it looks like you only modified the GUI, not the actual definition of the tactic or tech. I think the "real" part is contained within EncounterPlayDefinitions.xml, which you can see is where I previously added Collateral Damage to the tech tree (so you simply need to structurally emulate that to make it work for Team Spirit)

**Comment by FluffiestPrincess** [comment]
You're absolutely right; damn it. Moving back to draft until I've confirmed that's fixed.

**Comment by wakystuf** [comment]
Yep, this looks like it will work. I assume you tested that Team Spirit was actually available for use upon unlocking the respective tech? I'll merge today if so.

**Comment by FluffiestPrincess** [comment]
I did, yes.

**Review by wakystuf — APPROVED** [review]

**Pull request merged**
