### PR TITLE
Inflation-Oscillation-Fix

### PR DESCRIPTION
**Pull request by wakystuf**

### CODE REVIEW

**Comment by wakystuf** [comment]
1 line. Suck it @Arpharnator

**Review by Arpharnator — APPROVED** [review]

**Review by captaincobbs — CHANGES_REQUESTED** [review]
Lock Lumeris shadow banking to not be buildable until at least 1.25 inflation so that it doesn't get completely wasted

**Comment by Arpharnator** [comment]
cobb that's not how lumeris banking works

**Comment by captaincobbs** [comment]
> cobb that's not how lumeris banking works

How does it work then oh mighty one

**Comment by Arpharnator** [comment]
-25% total inflation felt on empire

ie : 100 inflation becomes 75 for them, not 99.75

**Comment by captaincobbs** [comment]
You're more wrong than I am, the minimum should 1.33

**Comment by Arpharnator** [comment]
whyyyyyyyyyyyyyyyyyyyyy

**Comment by captaincobbs** [comment]
Arphar and I came to the agreement that it shouldn't restrict you from using shadow banking if you have less than 1.333.. but it should make it clear that inflation can't go below 1.

**Review by Doruk-Coskun — APPROVED** [review]

**Pull request merged**
