### PR TITLE
Nerfed Riftborn Stasis Singularities

### PR DESCRIPTION
**Pull request by wakystuf**

### CODE REVIEW

**Comment by Doruk-Coskun** [comment]
@wakystuf @captaincobbs Can you explain the request please? Why is RB stasis nerf is bundled up with other things? And also why is RB stasis is being nerfed in the first place?

**Comment by wakystuf** [comment]
The bundling with other things is probably only caused by my inexperience at dealing with pushes; that wasn't something I did on purpose (Cap may have a more helpful explanation). Sorry about that.

When I first joined, I was complaining about RB stasis (the original mod that I wrote before I knew about ESG simply banned them), and a couple people told me that I didn't need to worry, because ESG already nerfed them to -30% science. I didn't see that in the code though, so I was including it here. Personally, I would nerf even more, but -30% is harsh enough that it's probably fine.

**Comment by captaincobbs** [comment]
It's not, he's just merging from an older branch

**Comment by Doruk-Coskun** [comment]
Rejected.

**Comment by wakystuf** [comment]
For the other 2 changes in this one (the caner hacking and Craver heroes) I'll create a separate pull request off the newer branch so that it's easier to see what I changed

**Pull request closed without merging**
