### PR TITLE
Starless Changes

### LINKED ISSUE #1339: Make starless system not insta bad
Make it possible for it to have 4 and 5 planets and make the chances of planet ammount match other star types instead of being 75%+ chance of 1 planet
allow ice, barren, ash and lava to spawn on them cuz it makes sense and increases variety
Really im just tired of skipping every starless i see  (unless they have a minor or something) cuz amplitude decided to make them trash for no reason. 
i even already have the code for this cuz i made it for another mod so its not like any effort would be required to make it happen.

### PR DESCRIPTION
**Pull request by Tat011**

### CODE REVIEW

**Comment by wakystuf** [comment]
Yeah, this looks good. 

Question: should these systems be guaranteed to be cold? Like include only the 2 cold gases, plus Barren and Ice? Lore-wise, I'm not sure where else the heat would come from if there's no star.

If nobody cares about that then I'll just merge, but lore would prob make more sense with cold.

**Comment by Tat011** [comment]
The heat would come from inside the planets, this is especially true for gas giants since irl big ones can do fusion like stars do. For rocky ones its similar since volcanoes spewing material from an active core could keep the surface hot

**Comment by Arpharnator** [comment]
yea but how is it even hot in the first place
space is cold af

**Comment by Tat011** [comment]
With what i just mentioned? Besides space isn't cold at all, vacuum can't transmit heat away so over heating is a thing that can very much happen

**Review by wakystuf — APPROVED** [review]

**Pull request merged**
