### PR TITLE
1083 gas giant anomalies dont work

### LINKED ISSUE #1083: Gas giant anomalies don't work.
In vanilla only warm gas giants had anomalies and thats cuz they had no temperature tag, but in esg they now do which means this kind of anomaly just straight up doesn't spawn at all. (btw i have a fixed version, i can just give it to you if you guys want)

### PR DESCRIPTION
**Pull request by FluffiestPrincess**
@Tat011 very helpfully contributed the code for this. I've checked and confirmed that more anomalies appear on gas giants, both hot and cold, with this file.

### CODE REVIEW

**Comment by FluffiestPrincess** [comment]
According to @Tat011, this code doesn't fully work with ESG because the additional anomalies setting adds anomalies using a quest, which doesn't take the anomalies definition file into account. But I _have_ tested this, and it _does_ result in more anomalies on gas giants.

**Comment by Tat011** [comment]
no it does work, its just that that specific setting ignores the spawning limitators (even vanilla ones) and plops anomalies werever, this is fine cuz no one uses that setting anyway imo

**Comment by captaincobbs** [comment]
The quest isn't too complicated to update, each anomaly type has its own prerequisites that should match the anomaly spawn conditions.

**Comment by Tat011** [comment]
ill look at it tomorrow

**Comment by wakystuf** [comment]
This looks like it should generally work. A few things:
1) First, thanks for uploading the file separately from modifying it! Makes it vastly easier to follow what's going on in the markup
2) What is the reason to convert certain anomalies from Mixed to Negative (ex: Long Season)?
3) Is it intended to add several restrictions that are unrelated to gas planets, such as on Mutated Flora? I'm not necessarily opposed to that, but just want to make sure I follow.

**Comment by Tat011** [comment]
2)Long season is negative in vanilla, either way in the mod i'm working on i tried changing some of the anomalies like that but i removed those changes before uploading the file so anomalies should remain the same quality as vanilla, its possible i missed something tho
3)Yeah pretty much all anomalies have had at least one change, in general the changes are as follows:
-it makes it more flexible when it comes to gas giants so you can get a lot of anomalies there that you previously couldn't like ice10 (only on the cold ones), meteor shower, psycoactive atmosphere, etc
-it removes dumb spawning like polar tempests on lava (this actually covers a lot since when it comes to non gas it was super lenient)
-it makes it possible for multiple of the same type (air, land, life, etc) to spawn on the same planet (the game didn't allow for this but only with some anomalies which was weird, plus since there are only 3 categories it becomes kinda arbitrary, like im pretty sure frindly locals is considered atmospheric which means you cant get it with dense atmosphere or psycoactive atmosphere)
-I noticed there was a strong bias towards positive anomalies for fertile and the opposite for sterile so i distributed some anomalies around as in: volcanic ones spawn only on hot, some dust ones don't spawn on fertile (since the lore says that dust doesn't get along with life), i wanted to give cold planets something but i only had humeris incidents.

**Comment by captaincobbs** [comment]
Just making sure, this is good for review?

**Comment by FluffiestPrincess** [comment]
Yes. Also:

>like im pretty sure frindly locals is considered atmospheric which means you cant get it with dense atmosphere or psycoactive atmosphere

Friendly, permanently stoned locals.

**Comment by wakystuf** [comment]
I just made some tweaks (for example, enabling Permanent Monsoon on Monsoon).

Should be all set, though would be great if someone could test (I'm on the road this week so testing is more annoying for me than usual).

**Review by captaincobbs — APPROVED** [review]

**Comment by captaincobbs** [comment]
Seems good to me, not going to double check that all the anomaly stuff matches up but at the very least I saw no immediate bugs. Merge when you're ready.

**Comment by Tat011** [comment]
> I just made some tweaks (for example, enabling Permanent Monsoon on Monsoon).

Can i ask what the tweaks are?
The reason monsoon didnt spawn on monsoon is because its already a defining feature of the planet, it's not weird for a monsoon planet to have monsoon, rather it'd be weird if it didn't

**Comment by Tat011** [comment]
ok i went through it and there is one thing
Why is polar tempest not cold only? i mean as is it can even spawn on lava

**Comment by wakystuf** [comment]
Normal monsoons are seasonal phenomena, not permanent

I haven't read the lore for the polar tempest in a long time, but I would think that a storm from one of the planet's poles could happen regardless of temperature; it's just a bunch of wind. Doesn't necessarily have to be cold, even though on Earth it indeed is. Maybe the lore says otherwise, however.

**Comment by Tat011** [comment]
You're right about monsoons.
Polar in polar tempest refers to its temperature, not its location, the picture and the planet graphic for the anomaly both show snowstorms and the planet graphic shown it covering the whole planet, the description is for the anomaly is this:
"Exceedingly cold winters and large continental masses drive this planet through cycles of violent weather. This results in heavy wear and tear on infrastructure, and makes farming--and life in general--unpleasant."

**Comment by wakystuf** [comment]
OK, in that case feel free to add a filter to prevent polar tempests from spawning on Hot

**Comment by Tat011** [comment]
i can't, i don't have permission

**Comment by wakystuf** [comment]
You do now :)

**Pull request merged**
