### PR TITLE
Update ES2_Localization_Tips.xml

### PR DESCRIPTION
**Pull request by Tat011**
I doubt this fixes it but maybe it will

### CODE REVIEW

**Comment by wakystuf** [comment]
Did you test it?

**Comment by Tat011** [comment]
This just removes the space before the file starts, tho no i didnt

**Comment by wakystuf** [comment]
Well test and see if it fixes the problem

**Comment by Tat011** [comment]
It does lol

**Review by wakystuf — APPROVED** [review]

**Comment by wakystuf** [comment]
OK I'll merge then

**Comment by Tat011** [comment]
Can you delete my 3 other branches too? thx

**Pull request merged**
