### PR TITLE
New implementation of lock-on modules

### LINKED ISSUE #1173: Proposal: nerf Antimatter Lock-on
> While we're at it, we should nerf Antimatter Lock-on. Stacking it with coordinator-only fleets is extremely strong in a similarly combat-breaking way. Maybe halve the damage boost or make it a unique boost per flotilla, if possible.

_Originally posted by @Eighth-of-Third in https://github.com/wakystuf/ESG-Mod/issues/1170#issuecomment-1120310765_

I'm creating a new issue for this because it'll get ignored entirely if it's only a comment on an otherwise unrelated issue, and I can't find Eighth-of-Third in the Discord to ask them about it.

- Do people think Antimatter Lock-On is a problem by itself?
- Do people think Antimatter Lock-On is a problem when used stacked in coordinator-only fleets?
- What's a good potential nerf, if one is needed?

For reference, Antimatter Lock-on is called `ModuleSupportAntiCarrier1Strategic4` in XML. It adds a 6% damage bonus "per target command point, on flotilla".

### PR DESCRIPTION
**Pull request by FluffiestPrincess**
This doesn't include any GUI changes, but frankly, the vanilla GUI doesn't properly display the effects of lock-on anyway.

### CODE REVIEW

**Comment by wakystuf** [comment]
Does this version work?
Also, I think you included the advanced effect in the antimatter version, didn't you? If I'm following correctly, then the advanced effect should be only for the strategic6 version of the module.

**Comment by FluffiestPrincess** [comment]
I think it works, yes. And I think the limiting effect also works.

Good catch on accidentally including the advanced effect in both modules; I fixed it.

**Comment by wakystuf** [comment]
Yeah the code looks like it should work. So as long as you (or someone else) has tested it with combat at the crazy values then it seems fine to merge

**Comment by wakystuf** [comment]
Can anyone confirm that this has been tested in a battle? I will merge if so

**Comment by Arpharnator** [comment]
the effect works, just tested.
However there is no description of the effect
image

**Comment by FluffiestPrincess** [comment]
Good spot, @Arpharnator . I fixed that now

**Review by Arpharnator — APPROVED** [review]
approve

**Pull request merged**
