### PR TITLE
WAK-Approval-Tweaks

### PR DESCRIPTION
**Pull request by wakystuf**

### CODE REVIEW

**Comment by captaincobbs** [comment]
This law seems very.. abusable

**Comment by captaincobbs** [comment]
Before I merge I think you need a cap

**Comment by wakystuf** [comment]
There are ~100 techs in the game, meaning that the hard cap is ~60 if someone manages to grab literally every tech in the game (by which point they could've won a science victory instead). That 60 is comparable to:
* 3 capitals with the miliarist law
* 3 alliances with the pacifist law
* 14 heroes with the religious law
* ~10 dedicated outposts for fuckery with the industrialist law

**Comment by captaincobbs** [comment]
Hmm that's fair, good point

**Pull request merged**
