### PR TITLE
Update for WeightTableDefinitions.xml

### PR DESCRIPTION
**Pull request by GitKopfkino**
Using WeightTableDefinitions.xml from Development-1-5-1, I've done a mostly visual update.
It's also my first time using Github to actually commit and push something, so I hope everything is ok and done correctly. I'm trying to push this to Development-1-5-1 and not the Main.
The DIFF Software doesn't understand that some things just changed from one line to another, and that I deleted a lot of blank space, so it thinks I changed values, which I didn't. Feel free to check manually, but most of the changes I made were:

- Correction of some entry mistakes, which were probably an oversight. For example there was a %StarName100 that should have been 200, because the 100 was before and correctly placed. I checked in Localization that each one actually existed.
Entry Tag="%StarName199"         Weight="1"
Entry Tag="%StarName100"         Weight="1"
Entry Tag="%StarName201"         Weight="1"

- I tried to visually uniformize the file, using mostly the same logic already present, such as using spaces instead of tabs and keeping things consistent. I have no actual coding experience, so I hope it's fine.

- Made a few text corrections, such as "Star blue" to "Blue Star"

- There were a few entry names that were skipped, or deleted? so I inserted a note in it's place for future reference, such as:
Entry Tag="%ActualStarName418"        Weight="1"
%ActualStarName419" unassigned
Entry Tag="%ActualStarName420"        Weight="1"

- Some entries ended in "/>>", which was probably an oversight, so I deleted the extra ">".

- I reordered a few lines alphabetically. I didn't change the order of any Weight Table, or anything like that; just inside each one if for some reason "Entry 25" was after "Entry 38".

Edit: Had to edit this message because GitHub was hiding the entries if fully written.

### CODE REVIEW

**Comment by Tat011** [comment]
Don't leave them unassigned, add them.

**Comment by Tat011** [comment]
looking at this i noticed Curiosity_PlanetAnomaly49 is missing

**Comment by GitKopfkino** [comment]
> Don't leave them unassigned, add them.

Will do. I believe they aren't Localized and I can't find their description anywhere, but I might not be looking in the right place.

**Comment by GitKopfkino** [comment]
> looking at this i noticed Curiosity_PlanetAnomaly49 is missing

Went to check and it's true. It wasn't present originally. I'll add it as well.

**Comment by Tat011** [comment]
did you intend to change the harmony spawn planets? id look  to see if others are different but the github comparison tool breaks down in that section

**Comment by Tat011** [comment]
which ones are missing localization?

**Comment by GitKopfkino** [comment]
> which ones are missing localization?

The ones I left unassigned. I'm rechecking nonetheless, and these don't have an entry on ES2_Localization_Names.xml:
"%StarNameRW2"
"%ActualStarName88"
"%ActualStarName241"
"%ActualStarName334"
"%ActualStarName385"
"%ActualStarName386"
"%ActualStarName387"
"%ActualStarName388"
"%ActualStarName419"

1. I'm unsure about this one because it's marked as Vanilla, so it might not have localization? - "%ConstellationName8" (it's under Name="ConstellationNames", and below --Vanilla--)
2. I'm also unsure about "PlanetAnomaly03" under "Name="AnomalyVisibleGeneration_Default", because it might be on purpose so it's invisible?

**Comment by GitKopfkino** [comment]
> did you intend to change the harmony spawn planets? id look to see if others are different but the github comparison tool breaks down in that section

That's why I mentioned the problem with the DIFF. It doesn't understand I changed some lines and spaces. I'll attach a printscreen so you can see the before and after. The values remain the same. It's the DIFF that it comparing wrong lines.

01  Before
02  After

**Comment by Tat011** [comment]
"%StarNameRW2" has been fixed, it wasnt broken tho, just skipped over
"%ActualStarName88" and all the other ones are very likely me messing up the number and not stuff missing, it doesn't really matter that the numbering is scuffed, just leave it as is

**Comment by captaincobbs** [comment]
Is this good to review? Also, there are conflicts you need to resolve before merging. Sorry, don't check the github often, feel free to message me if you have something that needs to be reviewed.

**Comment by Tat011** [comment]
What's conflicting? i tried to look at "resolve conflicts" but just got confused

**Review by Tat011 — APPROVED** [review]

**Pull request merged**
